# User config
author: "Michelle Vossen"
tagline: "Workshops, projects & experimental design research by Michelle Vossen"
description: "Michelle Vossen is an electronic textile designer based in Utrecht. Central to her work are artisanal approaches to electronics. She creates soft sensors from conductive and insulating materials with (manual) textile techniques. She explores hybrid forms of craft, textiles and technology.
<br><br>
She develops playful, interactive interfaces using electronic textiles and electronics. This results in touchable objects, installations and textile surfaces that can be used as input, for example, to make music or control machines. She also experiments with new ways for humans and machines to collaborate by building or hacking tools and machines herself. In this way, she creates processes in which human intervention continues to play a role, with textiles serving as both a means and a medium.
<br><br>
Major values surrounding her work are learning-by-making and open source documentation. She brings this methodology to various workshops and events that expand on her work throughout the year. If you want to collaborate, feel free to reach out through the e-mail listed below. 
<br><br>
Michelle is currently pursuing a Master's degree in Textile Interaction Design at the Swedish School of Textiles."
keywords: ["3d printing", "digital fashion", "experiments", "fashion"]
email: "studio@michellevossen.com"
linkedin: "https://www.linkedin.com/in/michelle-vossen-616842151/"
instagram: "https://instagram.com/michellevossen_"

# Site config
# baseurl: "/pineapple"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed


plugins:
- jekyll-toc

markdown: kramdown
kramdown:
  footnote_nr: 1